name = "DPack"
author = "DiefAlpha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41f14e6d2217cd7b528812bfcfa6fe4d12e875104a3ef6ed3869b2623da93ea9"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
