name = "DPack"
author = "DiefAlpha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "768504bc8056d8767ae2f4c473b3d21fd43d467b068eefaa661965a66a717585"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
