name = "DPack"
author = "DiefAlpha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00f4195d0b6a01b8766aec095a58ff24e5e11b0eb9e5e6b36adbf3d9e3918e5b"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
