name = "DPack"
author = "DiefAlpha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b9138a5f3a837fa6bb3756df35ce9c5cecc53f6c3d2696b63c08fcb4c2f70ca"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
