name: Export modpack
run-name: exporting modpack as .mrpack file
on: [push]
jobs:
  export-modpack:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0
        with:
          go-version: "^1.21"
      - name: Setup Packwiz
        run: go install github.com/packwiz/packwiz@latest
      - name: Export modpack
        run: |
          cd modpack
          packwiz mr export
      - name: Upload modpack
        uses: actions/upload-artifact@v3.1.2
        with:
          name: "modpack"
          path: "modpack/*.mrpack"
          if-no-files-found: error
          # using default
          retention-days: 0
